### ISSUE TITLE
Improve searching so people can search all the movies

### ISSUE THREAD

**Issue by LindseyB** [LindseyB/starwars-dot-gif#2]
Searching should be able to be done with all movies instead of having to pick one. This will be slower so it should be added as an additional option in the list.

**Comment by derdritte** [comment]
This is part of pull-request #32.
As requested, I have added it as the first option in the movie-selection menu.
I have also added some visual aid to help in the subtitle-selection menu following the search.

**Comment by LindseyB** [comment]
Closed by https://github.com/LindseyB/starwars-dot-gif/pull/32
