### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dogeared** [LindseyB/starwars-dot-gif#30]
Heyo!

I'm a developer, but a bit of a python `n00b`.

I've configured `config.cfg`.

It seems to be barfing on the `screencaps` folder. I made sure that the folder is there. 

This line sets the `screencap_path`:

```
screencap_path = os.path.join(os.path.dirname(__file__), "screencaps")
```

It just ends up being: `screencaps`.

I tried this on both Linux and Mac OSX and I get the same output.

**Comment by LindseyB** [comment]
Hi 👋 Can you post the full output of the error?

**Comment by dogeared** [comment]
Wow - thanks for the quick response. I got over that hump by changing the `subprocess.call` to:

```
subprocess.call("ffmpeg -i %s -ss %s -t %s %s" %(video_path, start, end, screencap_path + '/thumb%05d.png'), shell=True)
```

(seems like it didn't like the output template in the original form?

```
    subprocess.call([ffmpeg,
      '-i',
      video_path,
      '-ss',
      start,
      '-t',
      end,
      screencap_path + '/thumb%05d.png'
      ])
```

At any rate, here's the original error:

```
Traceback (most recent call last):
  File "makeGifs.py", line 261, in <module>
    makeGif(random.choice(args.episodes), sub_index=sub_index, rand=random_index, no_quote=no_quote, filename=args.filename)
  File "makeGifs.py", line 157, in makeGif
    screencap_path + '/thumb%05d.png'
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by dogeared** [comment]
Thanks for the help! I found that I was having trouble getting the gifs to create properly too. Turned out the be the version of pillow.

I setup this: https://github.com/dogeared/bojack-dot-gif

and this: https://twitter.com/BojackDotGif
