### ISSUE TITLE
pull-request(s) or fork?

### ISSUE THREAD

**Issue by derdritte** [LindseyB/starwars-dot-gif#31]
I saw this project a while ago and finally wanted to try it yesterday, sadly on my fedora-machine it had multiple issues:
- ffmpeg would not work at all (arguments out of order, expected strings …)
- vlc (still) throws a thousand errors (these appear to be benign?)
- screencap-folder was not present (vlc did complain about that too)
- Pillow murdered the gifs it created

I have spent a night fixing my issues, changing/refactoring some stuff and adding some new features.
I still have to modify the bots for the new function signatures but otherwise it appears to work fine (on my fedora machine).

My question is: would you accept major changes as:
a) a single pull request
b) multiple pull requests (no idea how I would manage that, the changes are all entangled)
c) just as well have me fork it and mess with it there

I am fairly knew to online collaboration so please let me know if I need to move/delete this or should have done something differently, thanks! I am happy to put up more detailed information on the specific issues, I just didn't want to flood the repo with stuff when there might be an easier way.

**Comment by LindseyB** [comment]
You can do one big PR if you would like. It's just be maintaining this so go for it.

**Comment by derdritte** [comment]
Thank you for the quick response, I'll work on it some more over the weekend, try to get some testing in and submit a pull-request.
